name = "wedding-rose-game"
main = "_worker.js"
compatibility_date = "2024-09-01"

[assets]
directory = "."
binding = "ASSETS"

pages_build_output_dir = "."

# Cloudflare D1 資料庫綁定
[[d1_databases]]
binding = "a1"
database_name = "a1"
database_id = "a1"
